@startuml
title Overview
object User
object ThemeData
object Settings
object PlayOptions
object Select
object Play
object Result {
    Achievement
}

User -- Settings : Change settings
User -- Select : Select from songs list
User -- PlayOptions : Select play option
User -- Play : Play selected the song
User -- Result : Check the play result
@enduml