@startuml
title Play
object Play
object User
object PlayResult
object SongMetadata
object SongBodyData {

}
object PlayThemeData

User -- Play : Playing
Play -- PlayResult : Record result
Play -- SongBodyData : Create song score
PlayThemeData -- Play : Applying play view theme
Play -- SongMetadata : Display to screen basic \n information of songs, \n get BPM, and so on
@enduml