@startuml
object Select
object SongsList {
    songHierarchy = "Top"
    songTitle = ""
    songDifficuly = "?"
}
object SongMetadata {
    player = 1
    rank = 3
    total = 160
    volwav = 100
    stageFile = ""
    banner = ""
    backBmp = ""
    playLevel = "?"
    difficulty = "?"
    title = "untitled"
    subTitle = "untitled"
    artist = "Anonymous"
    subArtist = "Anonymous"
    genre = "non genre"
    bpm = 130
    midifile = ""
}

Select -- SongsList : Display to screen songs list
Select -- SongMetadata : Display to screen basic information of songs
SongsList -- SongMetadata : Create songs list
@enduml